/**
 * @jest-environment node
 */
import { jest } from "@jest/globals";
import { updateStructure } from "./plantGrowth.mjs";
import { blockNames } from "../../world/config/blocks.mjs";

describe("Plant Restoration Regression", () => {
  let gameState;

  beforeEach(() => {
    gameState = {
      world: {
        get: jest.fn(),
        delete: jest.fn(),
        set: jest.fn(),
      },
      plantStructures: {},
    };
  });

  test("updateStructure with force=true should set blocks even if internal state hasn't changed", () => {
    const key = "10,20,30";
    const type = blockNames.MUSHROOM;

    // Initial call to set up the plant (it will call set, but we ignore it)
    gameState.plantStructures[key] = {
      type: type,
      blocks: [],
    };

    updateStructure(gameState, key, 1.0, type, false);

    gameState.world.set.mockClear();

    // Second call without force - should NOT call set/delete because state matches
    updateStructure(gameState, key, 1.0, type, false);
    expect(gameState.world.set).not.toHaveBeenCalled();

    // Reset mock counts
    gameState.world.set.mockClear();

    // Third call WITH force - SHOULD call set even if progress is same
    updateStructure(gameState, key, 1.0, type, true);

    // It should have called set for the blocks generated by the generator
    expect(gameState.world.set).toHaveBeenCalled();
  });

  test("updateStructure with force=true should handle missing blocks in world", () => {
    const key = "10,20,30";
    const type = blockNames.MUSHROOM;

    // Internal state says blocks exist
    gameState.plantStructures[key] = {
      type: type,
      blocks: [
        { x: 10, y: 20, z: 30, blockId: 5 },
        { x: 10, y: 21, z: 30, blockId: 5 },
      ],
    };

    // But world is empty (newly restored chunk)
    gameState.world.get.mockReturnValue(undefined);

    // Call WITH force
    updateStructure(gameState, key, 1.0, type, true);

    // Generator for Mushroom should have been called and blocks set in world
    // let's verify gameState.world.set was called
    expect(gameState.world.set.mock.calls.length).toBeGreaterThan(0);
  });
});
