/**
 * Block property definition.
 *
 * @typedef {Object} BlockDefinition
 *
 * @property {string} name - Display name of the block
 * @property {[number, number, number, number]} color - RGBA color
 * @property {number} [growthTime] - Time in seconds for plant to grow
 * @property {boolean} [isSeed=false] - Whether this block is a seed/plant
 * @property {boolean} [gravity=false] - Whether a block falls
 */

export const blockNames = {
  AIR: "Air",
  AGAVE_BASE: "Agave Base",
  AGAVE_FLOWER_STALK: "Agave Flower Stalk",
  AGAVE_FLOWER: "Agave Flower",
  AGAVE_GROWING: "Agave Growing",
  AGAVE_SPIKE: "Agave Spike",
  AGAVE: "Agave",
  BAMBOO_GROWING: "Bamboo Growing",
  BAMBOO_JOINT: "Bamboo Joint",
  BAMBOO_LEAVES: "Bamboo Leaves",
  BAMBOO_STALK: "Bamboo Stalk",
  BAMBOO: "Bamboo",
  BEDROCK: "Bedrock",
  BERRY_BUSH_BERRIES: "Berry Bush Berries",
  BERRY_BUSH_BRANCH: "Berry Bush Branch",
  BERRY_BUSH_GROWING: "Berry Bush Growing",
  BERRY_BUSH_LEAVES: "Berry Bush Leaves",
  BERRY_BUSH: "Berry Bush",
  BIRCH_BARK: "Birch Bark",
  BIRCH_BRANCHES: "Birch Branches",
  BIRCH_CATKINS: "Birch Catkins",
  BIRCH_GROWING: "Birch Growing",
  BIRCH_LEAVES: "Birch Leaves",
  BIRCH_TRUNK: "Birch Trunk",
  BIRCH: "Birch",
  CACTUS_BODY: "Cactus Body",
  CACTUS_FLOWER: "Cactus Flower",
  CACTUS_GROWING: "Cactus Growing",
  CACTUS: "Cactus",
  CARROT_GROWING: "Carrot Growing",
  CARROT_LEAVES: "Carrot Leaves",
  CARROT_ROOT: "Carrot Root",
  CARROT: "Carrot",
  CLAY: "Clay",
  CLOUD: "Cloud",
  COAL: "Coal",
  CORN_EAR: "Corn Ear",
  CORN_GROWING: "Corn Growing",
  CORN_LEAVES: "Corn Leaves",
  CORN_SILK: "Corn Silk",
  CORN_STALK: "Corn Stalk",
  CORN: "Corn",
  DIRT: "Dirt",
  FERN_FROND: "Fern Frond",
  FERN_GROWING: "Fern Growing",
  FERN_STEM: "Fern Stem",
  FERN: "Fern",
  FOG: "Fog",
  GOLD: "Gold",
  GRASS: "Grass",
  ICE: "Ice",
  IRON: "Iron",
  KELP_BLADE: "Kelp Blade",
  KELP_BULB: "Kelp Bulb",
  KELP_GROWING: "Kelp Growing",
  KELP: "Kelp",
  LAVA: "Lava",
  LAVENDER_BUSH: "Lavender Bush",
  LAVENDER_FLOWERS: "Lavender Flowers",
  LAVENDER_GROWING: "Lavender Growing",
  LAVENDER_STEM: "Lavender Stem",
  LAVENDER: "Lavender",
  LOTUS_BUD: "Lotus Bud",
  LOTUS_FLOWER: "Lotus Flower",
  LOTUS_GROWING: "Lotus Growing",
  LOTUS_PAD: "Lotus Pad",
  LOTUS_STEM: "Lotus Stem",
  LOTUS: "Lotus",
  MOSS: "Moss",
  MUSHROOM_CAP: "Mushroom Cap",
  MUSHROOM_GROWING: "Mushroom Growing",
  MUSHROOM_STEM: "Mushroom Stem",
  MUSHROOM: "Mushroom",
  PINE_CONE: "Pine Cone",
  PINE_NEEDLES: "Pine Needles",
  PINE_TREE_GROWING: "Pine Tree Growing",
  PINE_TREE: "Pine Tree",
  PINE_TRUNK: "Pine Trunk",
  PUMICE: "Pumice",
  PUMPKIN_FRUIT: "Pumpkin Fruit",
  PUMPKIN_GROWING: "Pumpkin Growing",
  PUMPKIN_LEAVES: "Pumpkin Leaves",
  PUMPKIN_STEM: "Pumpkin Stem",
  PUMPKIN_VINE: "Pumpkin Vine",
  PUMPKIN: "Pumpkin",
  ROSE_BLOOM: "Rose Bloom",
  ROSE_BUD: "Rose Bud",
  ROSE_GROWING: "Rose Growing",
  ROSE_LEAVES: "Rose Leaves",
  ROSE_STEM: "Rose Stem",
  ROSE_THORNS: "Rose Thorns",
  ROSE: "Rose",
  SAND: "Sand",
  SNOW: "Snow",
  STONE: "Stone",
  SUNFLOWER_CENTER: "Sunflower Center",
  SUNFLOWER_GROWING: "Sunflower Growing",
  SUNFLOWER_LEAVES: "Sunflower Leaves",
  SUNFLOWER_PETALS: "Sunflower Petals",
  SUNFLOWER_STEM: "Sunflower Stem",
  SUNFLOWER: "Sunflower",
  TREE_GROWING: "Tree Growing",
  TREE_LEAVES: "Tree Leaves",
  TREE_TRUNK: "Tree Trunk",
  TULIP_BULB: "Tulip Bulb",
  TULIP_GROWING: "Tulip Growing",
  TULIP_LEAVES: "Tulip Leaves",
  TULIP_PETALS: "Tulip Petals",
  TULIP_STEM: "Tulip Stem",
  TULIP: "Tulip",
  WATER: "Water",
  WHEAT_GRAIN: "Wheat Grain",
  WHEAT_GROWING: "Wheat Growing",
  WHEAT_STALK: "Wheat Stalk",
  WHEAT: "Wheat",
  WILLOW_BRANCHES: "Willow Branches",
  WILLOW_LEAVES: "Willow Leaves",
  WILLOW_TREE_GROWING: "Willow Tree Growing",
  WILLOW_TREE: "Willow Tree",
  WILLOW_TRUNK: "Willow Trunk",
  WOOD: "Wood",
};

export const FAST_GROWTH_TIME = 30;

/**
 * Array of block definitions.
 *
 * @type {BlockDefinition[]}
 */
export const blocks = [
  { name: blockNames.AIR, color: [0.0, 0.0, 0.0, 0.0] },
  { name: blockNames.AGAVE_BASE, color: [0.4, 0.6, 0.5, 1.0] },
  { name: blockNames.AGAVE_FLOWER_STALK, color: [0.5, 0.7, 0.5, 1.0] },
  { name: blockNames.AGAVE_FLOWER, color: [0.9, 0.9, 0.6, 1.0] },
  { name: blockNames.AGAVE_GROWING, color: [0.5, 0.7, 0.6, 1.0] },
  { name: blockNames.AGAVE_SPIKE, color: [0.4, 0.6, 0.5, 1.0] },
  {
    name: blockNames.AGAVE,
    color: [0.4, 0.6, 0.5, 1.0],
    growthTime: 1920,
    isSeed: true,
  },
  { name: blockNames.BAMBOO_GROWING, color: [0.4, 0.7, 0.4, 1.0] },
  { name: blockNames.BAMBOO_JOINT, color: [0.35, 0.65, 0.25, 1.0] },
  { name: blockNames.BAMBOO_LEAVES, color: [0.3, 0.6, 0.3, 1.0] },
  { name: blockNames.BAMBOO_STALK, color: [0.4, 0.7, 0.3, 1.0] },
  {
    name: blockNames.BAMBOO,
    color: [0.4, 0.7, 0.3, 1.0],
    growthTime: 180,
    isSeed: true,
  },
  { name: blockNames.BEDROCK, color: [0.1, 0.1, 0.1, 1.0] },
  { name: blockNames.BERRY_BUSH_BERRIES, color: [0.8, 0.2, 0.2, 1.0] },
  { name: blockNames.BERRY_BUSH_BRANCH, color: [0.4, 0.3, 0.2, 1.0] },
  { name: blockNames.BERRY_BUSH_GROWING, color: [0.4, 0.6, 0.4, 1.0] },
  { name: blockNames.BERRY_BUSH_LEAVES, color: [0.2, 0.5, 0.2, 1.0] },
  {
    name: blockNames.BERRY_BUSH,
    color: [0.3, 0.5, 0.3, 1.0],
    growthTime: 360,
    isSeed: true,
  },
  { name: blockNames.BIRCH_BARK, color: [0.8, 0.8, 0.75, 1.0] },
  { name: blockNames.BIRCH_BRANCHES, color: [0.85, 0.85, 0.8, 1.0] },
  { name: blockNames.BIRCH_CATKINS, color: [0.7, 0.6, 0.3, 1.0] },
  { name: blockNames.BIRCH_GROWING, color: [0.8, 0.9, 0.8, 1.0] },
  { name: blockNames.BIRCH_LEAVES, color: [0.3, 0.7, 0.3, 1.0] },
  { name: blockNames.BIRCH_TRUNK, color: [0.9, 0.9, 0.85, 1.0] },
  {
    name: blockNames.BIRCH,
    color: [0.9, 0.9, 0.85, 1.0],
    growthTime: 1260,
    isSeed: true,
  },
  { name: blockNames.CACTUS_BODY, color: [0.3, 0.6, 0.3, 1.0] },
  { name: blockNames.CACTUS_FLOWER, color: [0.9, 0.3, 0.5, 1.0] },
  { name: blockNames.CACTUS_GROWING, color: [0.4, 0.7, 0.4, 1.0] },
  {
    name: blockNames.CACTUS,
    color: [0.3, 0.6, 0.3, 1.0],
    growthTime: 2400,
    isSeed: true,
  },
  { name: blockNames.CARROT_GROWING, color: [0.5, 0.7, 0.3, 1.0] },
  { name: blockNames.CARROT_LEAVES, color: [0.3, 0.7, 0.3, 1.0] },
  { name: blockNames.CARROT_ROOT, color: [0.9, 0.5, 0.1, 1.0] },
  {
    name: blockNames.CARROT,
    color: [0.9, 0.5, 0.1, 1.0],
    growthTime: 240,
    isSeed: true,
  },
  { name: blockNames.CLAY, color: [0.7, 0.7, 0.75, 1.0] },
  { name: blockNames.CLOUD, color: [0.9, 0.9, 0.9, 0.8] },
  { name: blockNames.COAL, color: [0.15, 0.15, 0.15, 1.0] },
  { name: blockNames.CORN_EAR, color: [0.8, 0.8, 0.2, 1.0] },
  { name: blockNames.CORN_GROWING, color: [0.5, 0.7, 0.4, 1.0] },
  { name: blockNames.CORN_LEAVES, color: [0.3, 0.5, 0.3, 1.0] },
  { name: blockNames.CORN_SILK, color: [0.7, 0.6, 0.5, 1.0] },
  { name: blockNames.CORN_STALK, color: [0.4, 0.6, 0.3, 1.0] },
  {
    name: blockNames.CORN,
    color: [0.8, 0.8, 0.2, 1.0],
    growthTime: 420,
    isSeed: true,
  },
  { name: blockNames.DIRT, color: [0.55, 0.4, 0.25, 1.0] },
  { name: blockNames.FERN_FROND, color: [0.3, 0.6, 0.3, 1.0] },
  { name: blockNames.FERN_GROWING, color: [0.4, 0.6, 0.4, 1.0] },
  { name: blockNames.FERN_STEM, color: [0.3, 0.5, 0.3, 1.0] },
  {
    name: blockNames.FERN,
    color: [0.3, 0.6, 0.3, 1.0],
    growthTime: 90,
    isSeed: true,
  },
  { name: blockNames.GOLD, color: [0.9, 0.8, 0.1, 1.0] },
  { name: blockNames.GRASS, color: [0.3, 0.8, 0.3, 1.0] },
  { name: blockNames.ICE, color: [0.6, 0.8, 1.0, 0.7] },
  { name: blockNames.IRON, color: [0.7, 0.6, 0.5, 1.0] },
  { name: blockNames.KELP_BLADE, color: [0.2, 0.4, 0.2, 1.0] },
  { name: blockNames.KELP_BULB, color: [0.3, 0.5, 0.2, 1.0] },
  { name: blockNames.KELP_GROWING, color: [0.3, 0.5, 0.3, 1.0] },
  {
    name: blockNames.KELP,
    color: [0.2, 0.4, 0.2, 1.0],
    growthTime: 150,
    isSeed: true,
  },
  { name: blockNames.LAVA, color: [0.9, 0.3, 0.0, 1.0], gravity: true },
  { name: blockNames.LAVENDER_BUSH, color: [0.4, 0.6, 0.4, 1.0] },
  { name: blockNames.LAVENDER_FLOWERS, color: [0.55, 0.4, 0.6, 1.0] },
  { name: blockNames.LAVENDER_GROWING, color: [0.45, 0.3, 0.45, 1.0] },
  { name: blockNames.LAVENDER_STEM, color: [0.3, 0.4, 0.3, 1.0] },
  {
    name: blockNames.LAVENDER,
    color: [0.5, 0.3, 0.5, 1.0],
    growthTime: 200,
    isSeed: true,
  },
  { name: blockNames.LOTUS_BUD, color: [0.6, 0.4, 0.4, 1.0] },
  { name: blockNames.LOTUS_FLOWER, color: [0.7, 0.5, 0.5, 1.0] },
  { name: blockNames.LOTUS_GROWING, color: [0.4, 0.5, 0.4, 1.0] },
  { name: blockNames.LOTUS_PAD, color: [0.3, 0.5, 0.3, 1.0] },
  { name: blockNames.LOTUS_STEM, color: [0.4, 0.6, 0.4, 1.0] },
  {
    name: blockNames.LOTUS,
    color: [0.8, 0.6, 0.7, 1.0],
    growthTime: 390,
    isSeed: true,
  },
  { name: blockNames.MUSHROOM_CAP, color: [0.8, 0.2, 0.2, 1.0] },
  { name: blockNames.MUSHROOM_GROWING, color: [0.6, 0.5, 0.5, 1.0] },
  { name: blockNames.MUSHROOM_STEM, color: [0.9, 0.85, 0.8, 1.0] },
  {
    name: blockNames.MUSHROOM,
    color: [0.8, 0.6, 0.6, 1.0],
    growthTime: 120,
    isSeed: true,
  },
  { name: blockNames.PINE_CONE, color: [0.4, 0.3, 0.2, 1.0] },
  { name: blockNames.PINE_NEEDLES, color: [0.2, 0.4, 0.2, 1.0] },
  { name: blockNames.PINE_TREE_GROWING, color: [0.4, 0.6, 0.4, 1.0] },
  {
    name: blockNames.PINE_TREE,
    color: [0.2, 0.4, 0.2, 1.0],
    growthTime: 1440,
    isSeed: true,
  },
  { name: blockNames.PINE_TRUNK, color: [0.3, 0.2, 0.1, 1.0] },
  { name: blockNames.PUMICE, color: [0.7, 0.7, 0.7, 1.0] },
  { name: blockNames.PUMPKIN_FRUIT, color: [0.9, 0.5, 0.1, 1.0] },
  { name: blockNames.PUMPKIN_GROWING, color: [0.5, 0.7, 0.4, 1.0] },
  { name: blockNames.PUMPKIN_LEAVES, color: [0.3, 0.6, 0.3, 1.0] },
  { name: blockNames.PUMPKIN_STEM, color: [0.5, 0.6, 0.4, 1.0] },
  { name: blockNames.PUMPKIN_VINE, color: [0.4, 0.6, 0.3, 1.0] },
  {
    name: blockNames.PUMPKIN,
    color: [0.9, 0.5, 0.1, 1.0],
    growthTime: 660,
    isSeed: true,
  },
  { name: blockNames.ROSE_BLOOM, color: [0.9, 0.1, 0.2, 1.0] },
  { name: blockNames.ROSE_BUD, color: [0.7, 0.2, 0.3, 1.0] },
  { name: blockNames.ROSE_GROWING, color: [0.4, 0.7, 0.4, 1.0] },
  { name: blockNames.ROSE_LEAVES, color: [0.2, 0.6, 0.2, 1.0] },
  { name: blockNames.ROSE_STEM, color: [0.2, 0.5, 0.2, 1.0] },
  { name: blockNames.ROSE_THORNS, color: [0.3, 0.4, 0.3, 1.0] },
  {
    name: blockNames.ROSE,
    color: [0.9, 0.1, 0.2, 1.0],
    growthTime: 540,
    isSeed: true,
  },
  { name: blockNames.SAND, color: [0.9, 0.85, 0.6, 1.0], gravity: true },
  { name: blockNames.SNOW, color: [0.95, 0.95, 1.0, 1.0] },
  { name: blockNames.STONE, color: [0.5, 0.5, 0.5, 1.0] },
  { name: blockNames.SUNFLOWER_CENTER, color: [0.4, 0.3, 0.1, 1.0] },
  { name: blockNames.SUNFLOWER_GROWING, color: [0.5, 0.7, 0.4, 1.0] },
  { name: blockNames.SUNFLOWER_LEAVES, color: [0.3, 0.6, 0.3, 1.0] },
  { name: blockNames.SUNFLOWER_PETALS, color: [0.9, 0.8, 0.1, 1.0] },
  { name: blockNames.SUNFLOWER_STEM, color: [0.3, 0.5, 0.3, 1.0] },
  {
    name: blockNames.SUNFLOWER,
    color: [0.9, 0.8, 0.1, 1.0],
    growthTime: 600,
    isSeed: true,
  },
  { name: blockNames.TREE_GROWING, color: [0.4, 0.6, 0.3, 1.0] },
  { name: blockNames.TREE_LEAVES, color: [0.2, 0.6, 0.2, 1.0] },
  { name: blockNames.TREE_TRUNK, color: [0.45, 0.3, 0.15, 1.0] },
  { name: blockNames.TULIP_BULB, color: [0.6, 0.5, 0.4, 1.0] },
  { name: blockNames.TULIP_GROWING, color: [0.6, 0.8, 0.6, 1.0] },
  { name: blockNames.TULIP_LEAVES, color: [0.4, 0.7, 0.4, 1.0] },
  { name: blockNames.TULIP_PETALS, color: [0.8, 0.4, 0.8, 1.0] },
  { name: blockNames.TULIP_STEM, color: [0.5, 0.8, 0.5, 1.0] },
  {
    name: blockNames.TULIP,
    color: [0.8, 0.4, 0.8, 1.0],
    growthTime: 300,
    isSeed: true,
  },
  { name: blockNames.WATER, color: [0.2, 0.4, 0.8, 0.6], gravity: true },
  { name: blockNames.WHEAT_GRAIN, color: [0.9, 0.85, 0.4, 1.0] },
  { name: blockNames.WHEAT_GROWING, color: [0.5, 0.7, 0.3, 1.0] },
  { name: blockNames.WHEAT_STALK, color: [0.8, 0.8, 0.4, 1.0] },
  {
    name: blockNames.WHEAT,
    color: [0.85, 0.8, 0.4, 1.0],
    growthTime: 480,
    isSeed: true,
  },
  { name: blockNames.WILLOW_BRANCHES, color: [0.4, 0.6, 0.3, 1.0] },
  { name: blockNames.WILLOW_LEAVES, color: [0.5, 0.7, 0.4, 1.0] },
  { name: blockNames.WILLOW_TREE_GROWING, color: [0.5, 0.6, 0.4, 1.0] },
  {
    name: blockNames.WILLOW_TREE,
    color: [0.5, 0.5, 0.3, 1.0],
    growthTime: 1800,
    isSeed: true,
  },
  { name: blockNames.WILLOW_TRUNK, color: [0.5, 0.35, 0.2, 1.0] },
  { name: blockNames.WOOD, color: [0.6, 0.45, 0.25, 1.0] },
];
